### ISSUE TITLE
"Magic Mirror" does not start

### ISSUE THREAD

**Issue by Lordy-Pi59** [lavolp3/MMM-Celebrations#1]
Hello,

my "Magic Mirror" does not start after I install the module "MMM-Celebrations".
Please help.

Magic Mirror Version: 2.90
npm Version: 6.10.3
node Version: 12.10.0

**Comment by lavolp3** [comment]
Please do a `git pull`. I hope it's solved. 
If it still does not work, please remove the whole folder and clone it again.

**Comment by lavolp3** [comment]
cheerio package installation instruction was missing in package.json. Corrected now in commit 7da1239
